<a href="https://colab.research.google.com/github/Vivek-afk81/ml-workshop/blob/main/Transformer_HuggingFace_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Generation

In [1]:
# TEXT generation using gpt 2 from hugging face lib
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")  # the task you want to do and the model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [2]:
prompt="what is deep learning"
output=pipe(prompt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [3]:
print(output[0]["generated_text"])

what is deep learning?

A lot of people who are experts at deep learning are pretty good at it. I think that it's pretty cool to be able to talk to people who are very knowledgeable about deep learning from a technical perspective, and really get an idea of what it is. That's how I got started.

How did you come up with the idea of deep learning?

I was fascinated by deep learning and the concept of the Turing test. I started doing research on how to measure and quantify how much information we can expect to see in a computer system when it's being used as teaching material. I thought it was something that should be very easy to build, but I was very skeptical about the theory and the theory wasn't quite getting to the point where I was willing to go that far.

What do you think of the idea that Deep Learning could be used to train an AI?

I think of it as an AI that learns by recognizing the similarities between objects and things. I don't think people have a good understanding of how to use a Turing test to measure this kind of thing, but that's what I think is the underlying idea.

Is there any kind of philosophical question or philosophical problem, or something that you would like

Loading the model directly

In [4]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [5]:
tokenizer

GPT2Tokenizer(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [6]:
#architecture of gpt2
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

### loading model directly from colab

In [7]:
from transformers import AutoTokenizer

In [8]:
tokenizer=AutoTokenizer.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [9]:
sentence="step-by-step"
input_ids=tokenizer(sentence) #this will return a dictionary
#converting into tensors
input_ids=tokenizer(sentence,return_tensors="pt")
input_ids=input_ids['input_ids']

In [10]:
tokenizer.decode(input_ids[0])

'step-by-step'

In [11]:
sentence="unbelivable"
input_ids=tokenizer(sentence,return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [12]:
for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

un
bel
ivable

In [13]:
word="homoscedasticity"
my_ids=tokenizer.encode(word,return_tensors="pt")
my_ids

tensor([[26452,   418,   771,  3477,   414]])

In [14]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids = tokenizer(word, return_tensors="pt").input_ids
len(my_ids[0])

15

In [15]:
for token_id in my_ids.squeeze():
  print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis

In [16]:
word = "floccinaucinihilipilification"

my_ids = tokenizer(word, return_tensors="pt").input_ids
my_ids, len(my_ids[0])

(tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]]), 9)

In [17]:
for token_id in my_ids[0]:
  print(tokenizer.decode(token_id))

fl
occ
in
auc
in
ihil
ip
il
ification

### Generate using gpt2

In [18]:
from transformers import AutoModelForCausalLM
import torch
import torch.nn.functional as F

In [19]:
gpt2=AutoModelForCausalLM.from_pretrained("gpt2")

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [20]:
sentence=" I learn machine learning to enhance the performance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

# print(gpt2(token_ids).logits.shape)
outputs=gpt2(token_ids).logits[0, -1]
tokenizer.decode(outputs.argmax())

' of'

In [21]:
sentence=" I learn machine learning to enhance the"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0, -1]
final_logits=torch.topk(outputs,7)
print(final_logits)

for index in final_logits.indices:
  print(tokenizer.decode(index))

torch.return_types.topk(
values=tensor([-110.0572, -110.1733, -110.5066, -110.7839, -110.9877, -111.2124,
        -111.2453], grad_fn=<TopkBackward0>),
indices=tensor([2854, 2836, 1692, 2694, 4673, 1998, 9332]))
 performance
 user
 human
 ability
 learning
 experience
 efficiency

In [22]:
sentence="I learn machine learning to enhance"

token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0,-1]
tokenizer.decode(outputs.argmax())

' our'

### Sampling Techniques

In [23]:
print(gpt2(token_ids).logits.shape)

torch.Size([1, 6, 50257])

In [24]:
def greedy_decode(logits):
  """Return token index with maximum probablity"""
  return torch.argmax(logits,dim=-1) # dim =-1 because argmax() operate on the last dimension vocab


#TOP K SAMPLING

def top_k_sampling(logits,k=30):
  """keeps only top k logits,normalize them into probablity.
  then sample one token fro the filtered distribution"""

  #unpacking

  values,indices=torch.topk(logits,k)
  #torch.topk returns -> values: the top k highest logits, indices: their positions (token IDs)

  probs=F.softmax(values,dim=-1)
  sampled=torch.multinomial(probs,1)
  return indices[sampled]


# TOP-p SAMPLING

def top_p_sampling(logits,p=0.9):

  """sort the tokens by probablity keep smallest number whose  cumulative probablity exceeds threshold p,
    then sample one token"""
  sorted_logits,sorted_indices=torch.sort(logits,descending=True)
  sorted_probs=F.softmax(sorted_logits,dim=-1)
  cumulative_probs=sorted_probs.cumsum(dim=-1)

  #Mask token outside the threshold
  mask=cumulative_probs>p
  sorted_logits[mask]=float("-inf")

  #Sample rom filtered logits

  filtered_probs = F.softmax(sorted_logits,dim=-1)
  sampled=torch.multinomial(filtered_probs,1)

  # Return token index in originial vocabulary
  return sorted_indices[sampled]


#TEMPERATURE SAMPLING

"""
    Scale logits by temperature before sampling.
    Lower temperature => sharper distribution
"""

def temperature_sampling(logits, temperature=1.0):
  scaled= logits/temperature
  probs=F.softmax(scaled,dim=-1)
  return torch.multinomial(probs,1)


#RANDOM SAMPLING

def random_sampling(logits):
    """
    Sample dirctly from softmax distribution without filtring
    """

    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)

In [25]:
sentence = "I am really happy becuase I have gone back in time.I"
inputs = tokenizer(sentence, return_tensors="pt")
output = gpt2(**inputs)
logits = output.logits[0, -1]

#outputs of different sampling strategies
print(f"Greedy Decode: ", tokenizer.decode([greedy_decode(logits)]))
print(f"Top-K Sampling: ", tokenizer.decode(top_k_sampling(logits, k=10)))
print(f"Top-P-Sampling: ", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print(f"Temp: ", tokenizer.decode(temperature_sampling(logits, temperature=1)))
print(f"Random: ", tokenizer.decode(random_sampling(logits)))

Greedy Decode:   am
Top-K Sampling:   was
Top-P-Sampling:   hope
Temp:   think
Random:   am

### **visualizing** the confidence for every token

In [26]:
sentence="i learn machine learning to enhance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

outputs=gpt2(token_ids).logits #Raw unnormalized outputs
#outputs[0,-1] # last token
outputs=torch.softmax(outputs[0,-1],dim=-1)

top10=torch.topk(outputs,k=10)

for index,value in zip(top10.indices,top10.values):
  print(f"{tokenizer.decode(index)} -- {value:.1}")

 the -- 0.1
 your -- 0.08
 their -- 0.06
 our -- 0.06
 its -- 0.06
 his -- 0.04
 human -- 0.02
 my -- 0.02
 her -- 0.01
 a -- 0.01

# Sentiment Analysis

In [27]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [28]:
type(ds)

datasets.dataset_dict.DatasetDict

In [29]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [30]:
ds["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [31]:
import pandas as pd

In [32]:
ds["train"].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [33]:
my_dataset_df=ds["train"].to_pandas()

In [34]:
my_dataset_df["text"]

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [35]:
len(my_dataset_df["text"])

25000

In [36]:
from transformers import pipeline

In [37]:
classifier=pipeline("sentiment-analysis",model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [38]:
classifier("this day is great")

[{'label': 'POSITIVE', 'score': 0.9998873472213745}]

In [39]:
classifier("this day is worst,nothing is going my way")

[{'label': 'NEGATIVE', 'score': 0.9997852444648743}]

In [40]:
#fetching the labels only
result=classifier("this day is worst,nothing is going my way")[0]
print(result["label"])

NEGATIVE

In [41]:
def score(review_text):
  return classifier(review_text[:500])[0]["label"]

In [43]:
my_dataset_df["model_prediction"]=my_dataset_df["text"].apply(score)

In [44]:
 my_dataset_df

,text,label,model_prediction
0,I rented I AM CURIOUS-YELLOW from my video sto...,0,NEGATIVE
1,"""I Am Curious: Yellow"" is a risible and preten...",0,NEGATIVE
2,If only to avoid making this type of film in t...,0,NEGATIVE
3,This film was probably inspired by Godard's Ma...,0,POSITIVE
4,"Oh, brother...after hearing about this ridicul...",0,NEGATIVE
...,...,...,...
24995,A hit at the time but now better categorised a...,1,NEGATIVE
24996,I love this movie like no other. Another time ...,1,POSITIVE
24997,This film and it's sequel Barry Mckenzie holds...,1,POSITIVE
24998,'The Adventures Of Barry McKenzie' started lif...,1,NEGATIVE
24999,The story centers around Barry McKenzie who mu...,1,POSITIVE

In [49]:
#true label is 1 but predicted sentiment is negative
my_dataset_df.iloc[24995]

text                A hit at the time but now better categorised a...
label                                                               1
model_prediction                                             NEGATIVE
Name: 24995, dtype: object

### Using another model Finbert

In [50]:
from transformers import pipeline

In [51]:
finbert=pipeline("sentiment-analysis",model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [52]:
sentence="the company reported a stron increase increase in quarterly revenue,exceeding market expectations"

finbert(sentence)

[{'label': 'positive', 'score': 0.9531447887420654}]

In [53]:
sentences = ["Strong consumer demand drove record sales across all regions",
"Supply chain disruptions severly affected production output"]

finbert(sentences)

[{'label': 'positive', 'score': 0.9434745907783508},
 {'label': 'negative', 'score': 0.9608097672462463}]

###Named Entity Recognition

Named Entity Recognition (NER) is a core task in Natural Language Processing (NLP) that automatically identifies and classifies key information—like names of people, places, organizations, dates, and monetary values—within text.

In [57]:
sentence ="Apple announced record earnings in the United States on Monday."

In [58]:
ner=pipeline("ner") #Checking the default model -> dbmdz/bert-large-cased-finetuned-conll03-english

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [59]:
ner(sentence)

[{'entity': 'I-ORG',
  'score': np.float32(0.9991387),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-LOC',
  'score': np.float32(0.9997105),
  'index': 7,
  'word': 'United',
  'start': 39,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.99967074),
  'index': 8,
  'word': 'States',
  'start': 46,
  'end': 52}]

In [60]:
text = "Microsoft announced a partnership with OpenAI in Paris on 5th May 2025."

ner(text)

[{'entity': 'I-ORG',
  'score': np.float32(0.99958104),
  'index': 1,
  'word': 'Microsoft',
  'start': 0,
  'end': 9},
 {'entity': 'I-ORG',
  'score': np.float32(0.9989538),
  'index': 6,
  'word': 'Open',
  'start': 39,
  'end': 43},
 {'entity': 'I-ORG',
  'score': np.float32(0.9961557),
  'index': 7,
  'word': '##A',
  'start': 43,
  'end': 44},
 {'entity': 'I-ORG',
  'score': np.float32(0.9981846),
  'index': 8,
  'word': '##I',
  'start': 44,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.99971277),
  'index': 10,
  'word': 'Paris',
  'start': 49,
  'end': 54}]

### Question Answering

In [61]:
qa_bot=pipeline("question-answering") #default model distilbert

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [62]:
context="""Financial sentiment analysis is a challenging task due to the
 specialized language and lack of labeled data in that domain.
General-purpose models are not effective enough because of the specialized
 language used in a financial context. We
hypothesize that pre-trained language models can help with this problem because
 they require fewer labeled examples and
they can be further trained on domain-specific corpora. We introduce FinBERT,
 a language model based on BERT, to tackle
NLP tasks in the financial domain. Our results show improvement in every
 measured metric on current state-of-the-art results
for two financial sentiment analysis datasets. We find that even with a smaller
 training set and fine-tuning only a part of the
model, FinBERT outpertorms state-ot-the-art machine learing methods."""

In [63]:
question="what is financial sentiment analysis"

In [65]:
qa_bot(question=question,context=context) #this mimics RAG

{'score': 0.04791763424873352,
 'start': 0,
 'end': 50,
 'answer': 'Financial sentiment analysis is a challenging task'}